name: dingjia
channels:
  - defaults
  - conda-forge
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - cudatoolkit=11.8.0=hd77b12b_0
  - expat=2.7.1=h8ddb27b_0
  - faiss=1.9.0=py311cuda118he08421d_0_cuda
  - faiss-gpu=1.9.0=hef1f8eb_0
  - fastapi=0.116.1=py311haa95532_0
  - idna=3.11=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - libblas=3.9.0=26_win64_mkl
  - libcblas=3.9.0=26_win64_mkl
  - libfaiss=1.9.0=cuda118h51f90d9_0_cuda
  - libffi=3.4.4=hd77b12b_1
  - liblapack=3.9.0=26_win64_mkl
  - libzlib=1.3.1=h02ab6af_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - numpy=1.26.4=py311h0b4df5a_0
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py311haa95532_1
  - pip=25.2=pyhc872135_1
  - pydantic-core=2.41.4=py311h114bc41_0
  - python=3.11.14=h981015d_0
  - python_abi=3.11=2_cp311
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - starlette=0.47.3=py311haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.15=hf199647_0
  - typing-extensions=4.15.0=py311haa95532_0
  - typing-inspection=0.4.2=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - accelerate==1.11.0
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - attrs==25.4.0
      - backoff==2.2.1
      - beautifulsoup4==4.14.2
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - cryptography==46.0.3
      - dataclasses-json==0.6.7
      - dill==0.4.0
      - distro==1.9.0
      - docling==2.58.0
      - docling-core==2.49.0
      - docling-ibm-models==3.10.1
      - docling-parse==4.7.0
      - easyocr==1.7.2
      - emoji==2.15.0
      - et-xmlfile==2.0.0
      - faker==37.12.0
      - filelock==3.20.0
      - filetype==1.2.0
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - greenlet==3.2.4
      - h11==0.16.0
      - html5lib==1.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - imageio==2.37.0
      - jinja2==3.1.6
      - jiter==0.11.1
      - joblib==1.5.2
      - jsonlines==4.0.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - langchain==1.0.2
      - langchain-classic==1.0.0
      - langchain-community==0.4
      - langchain-core==1.0.1
      - langchain-huggingface==1.0.0
      - langchain-openai==1.0.1
      - langchain-text-splitters==1.0.0
      - langdetect==1.0.9
      - langgraph==1.0.1
      - langgraph-checkpoint==3.0.0
      - langgraph-prebuilt==1.0.1
      - langgraph-sdk==0.2.9
      - langsmith==0.4.38
      - latex2mathml==3.78.1
      - lazy-loader==0.4
      - lxml==5.4.0
      - markdown-it-py==4.0.0
      - marko==2.2.1
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - mpire==2.10.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - networkx==3.5
      - ninja==1.13.0
      - nltk==3.9.2
      - olefile==0.47
      - omegaconf==2.3.0
      - onnxruntime==1.23.2
      - openai==2.6.1
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - openpyxl==3.1.5
      - orjson==3.11.4
      - ormsgpack==1.11.0
      - pandas==2.3.3
      - pillow==11.3.0
      - pluggy==1.6.0
      - polyfactory==2.22.3
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.1
      - pyclipper==1.3.0.post6
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-settings==2.11.0
      - pygments==2.19.2
      - pylatexenc==2.10
      - pypdf==6.1.3
      - pypdfium2==4.30.0
      - pyreadline3==3.5.4
      - python-bidi==0.6.7
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - python-dotenv==1.1.1
      - python-iso639==2025.2.18
      - python-magic==0.4.27
      - python-multipart==0.0.20
      - python-oxmsg==0.0.2
      - python-pptx==1.0.2
      - pytz==2025.2
      - pywin32==311
      - pyyaml==6.0.3
      - rapidfuzz==3.14.1
      - rapidocr==3.4.2
      - rapidocr-onnxruntime==1.4.4
      - referencing==0.37.0
      - regex==2025.10.23
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - rtree==1.4.1
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.4.2
      - scipy==1.11.3
      - semchunk==2.2.2
      - sentence-transformers==5.1.2
      - shapely==2.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - torch==2.9.0+cu126
      - torchaudio==2.9.0+cu126
      - torchvision==0.24.0+cu126
      - tqdm==4.67.1
      - transformers==4.57.1
      - typer==0.19.2
      - typing-inspect==0.9.0
      - tzdata==2025.2
      - unstructured==0.18.15
      - unstructured-client==0.42.3
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - webencodings==0.5.1
      - wrapt==2.0.0
      - xlsxwriter==3.2.9
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: C:\Users\zx\anaconda3\envs\dingjia
